project_id = "jqvcafbrccpmygiihyry"

[functions.widget-loader]
verify_jwt = false

[functions.widget-config]
verify_jwt = false

[functions.send-chat-message]
verify_jwt = false

[functions.send-bug-report]
verify_jwt = false

[functions.track-widget-event]
verify_jwt = false
